name: Fetch Commits and create issue with details

# on:
#   schedule:
#     - cron: '* * * * *'  # Runs daily at midnight UTC

on:
  push:
    branches: [ master ]

jobs:
  fetch-and-create-pr:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository gtfs-validator
        uses: actions/checkout@v4.0.0
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.FRED_PERSONAL_GITHUB_TOKEN }} 

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Set up Git
        id: git-setup
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "user_name=github-actions[bot]" >> $GITHUB_OUTPUT
          echo "user_email=41898282+github-actions[bot]@users.noreply.github.com" >> $GITHUB_OUTPUT
          echo "reviewer=emmambd" >> $GITHUB_OUTPUT 
          echo "assigned=fredericsimard" >> $GITHUB_OUTPUT
        # Comma-separated list of reviewers and assignees

      - name: Calculate Dates
        id: dates
        run: |
          echo "yesterday=$(date -d '-1 day' '+%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Extract and process JSON
        id: process_json
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.request('GET /repos/google/transit/commits', {
              owner: 'fredericsimard',
              repo: 'gtfs-validator-fork',
              path: 'gtfs/spec/en/reference.md',
              since: '2023-08-01T00:00:00Z',
            });
            
            const commits = response.data;
            core.setOutput('commits_data', commits);
            core.setOutput('commits_length', commits.length);
      
            if (commits.length > 0) {
              const extractedData = commits.map(item => ({
                author: item.commit.author.name,
                date: item.commit.author.date,
                message: item.commit.message,
                html_url: item.html_url
              }));
              const formattedExtractedData = extractedData.map(item => {
                return `### Author: ${item.author}\n### Date: ${item.date}\n### Message\n\n${item.message}\n\n### Details\nClick here for more information: ${item.html_url}\n\n---------------------------\n\n`;
              }).join('\n');
              
              core.setOutput('extracted_data', formattedExtractedData);
              core.setOutput('condition_met', 'true');

            } else {
              core.setOutput('extracted_data', '[]');
              core.setOutput('condition_met', 'false');
            }
      
           # core.setOutput('extracted_data', JSON.stringify(extractedData));

      - name: Create Issue
        if: steps.process_json.outputs.condition_met == 'true'
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.FRED_PERSONAL_GITHUB_TOKEN }}
          title: Changes made to reference.md in the Google Transit repo.
          body: |
            # Changes made to `reference.md` from Google Transit's repo
            ## Date: ${{ steps.dates.outputs.today }}
            ## Number of new commits: ${{ steps.process_json.outputs.commits_length }}
            ---
            ## Raw data:
            ${{ steps.process_json.outputs.extracted_data }}
          assignees: ${{ steps.git-setup.outputs.assigned }}